networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./back
      network: host 
    networks:
      - dev
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "pypi.org:151.101.0.223"
      - "pypi.python.org:151.101.0.223"

    restart: always

  frontend:
    build:
      context: ./wakeup
      network: host
    networks:
      - dev
    restart: always
