# wakeup-site/docker-compose.yml

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
      # <--- ИЗМЕНЕНИЕ: Пробрасываем папку с аватарами в Nginx для раздачи
      - "./data/avatars:/usr/share/nginx/html/static/avatars:ro"
    restart: always
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./back
      network: host
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
    restart: always

  frontend:
    build:
      context: ./wakeup
      network: host
    restart: always