networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./back
      network: host   # позволит pip нормально тянуть зависимости
    networks:
      - dev
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "pypi.org:151.101.0.223"
      - "pypi.python.org:151.101.0.223"

  frontend:
    build: ./wakeup
    networks:
      - dev
